name: Lychee Link Checking

on:
  # Run on PRs targeting main that change content files.
  pull_request:
    branches: [main]
    paths: ['**/*.mdx?']
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  link-check:
    name: Lychee Link Checking
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    steps:
    - name: Check out repo
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Get changed content files
      id: changed-mdx-files
      uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
      with:
        files: |
          **.mdx

    - name: Run Lychee
      uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
      with:
        fail: false
        format: markdown
        jobSummary: true
        args: >
          -c lychee.toml
          --root-dir "$(pwd)"
          ${{ steps.changed-mdx-files.outputs.all_changed_files }}

    - name: Comment on PR with link check results
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
      with:
        path: lychee/out.md
