name: SCA

on:
  push:
    branches: ["main", "chore/add-synk-scanner"] # TOD: remove chore/add-synk-scanner branch after testing

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      additional-arguments: "--exclude=README.md,.jfrog"
    secrets: inherit
