name: Vale

on:
  pull_request:
    paths:
      # Add paths to files we want Vale to check
      - 'auth4genai/**/*.md'
      - 'auth4genai/**/*.mdx'
      - 'auth4genai/**/*.jsx'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Install mdx2vast
        run: npm install -g mdx2vast

      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          files: '["auth4genai/"]'
          fail_on_error: true
